"""
Problem 1 : Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
def even_fibonacci_numbers(n):
    count=0
    sum=0
    oldFib =1
    newFib =1
    curFib=0
    while(curFib <= n):
        curFib = oldFib+newFib
        if (curFib%2 ==0):
            sum = sum + curFib
        oldFib =newFib
        newFib =curFib
    return sum


if __name__ == "__main__":
    print(even_fibonacci_numbers(4000000))